name: Build Portable OverlayDetect

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Compile overlay_detect.exe
        run: g++ overlay_detect.cpp -o overlay_detect.exe -lpsapi -static

      - name: Upload .exe
        uses: actions/upload-artifact@v3
        with:
          name: OverlayDetectEXE
          path: overlay_detect.exe

